version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pythonproject:latest
    container_name: pythonproject
    # 添加自动重启策略
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    # 健康检查
    healthcheck:
      test: ["CMD", "pythonproject", "--version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    # 安全设置
    security_opt:
      - no-new-privileges:true
    # 添加日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # 如果是命令行工具，可以取消下面的注释并调整命令
    # command: ["--config", "/app/config/config.yml"]

  # 示例: 如果你的应用需要数据库
  # db:
  #   image: postgres:16-bookworm
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=pythonproject
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

# 添加网络配置
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    # 增加网络安全性
    driver_opts:
      com.docker.network.bridge.name: pythonproject_net
      com.docker.network.driver.mtu: 1500

# 如使用数据库，取消下面的注释
# volumes:
#   postgres_data:
