name: Python publish to pypi

on:
  push:
    tags:
      - 'v*'  # 自动：推送带v前缀的标签时触发
  workflow_dispatch:  # 手动：允许在Actions手动运行
    inputs:
      tag_name:
        description: '发布的版本号（例如：v1.0.0）'
        required: true

jobs:
  publishToPyPI:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install build wheel setuptools twine

    - name: 构建包
      run: python -m build

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

    - name: 创建 GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        files: |
          dist/*.whl
          dist/*.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: 发布到PyPI
      run: |
        python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
